language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
dist: trusty
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: PNuxPLaqfJU1G1dU5udy3RRCALE+mDcBNqyNwTm3THzHZEY8I/0TGACgN/iYSIqhYXRDeBgrsTClbAu/HP6S/actgiKY5XtVGqYjM1ZNXQT2jTB9LzrEyuT565OX5XbHCdK38Vh6SBdp/qy3B7+raPR6wjCzLTCspUzJIZYcuCoXQkparsn/EFcDvuQE7d4ttVdd0fLq6zMOXRIAbUmRD5gEn7bz+yA/IeVtsdx3pR71DHAL/Wn+Owyynf1KtYnwprxN3LgeTTvhU74nWWBbLt6uGotzs3n24Ug/BkhF8v3f1waOYmX7vM5eQvRYNfFD6DIra4P1gKJfLzBaHRzyGK67kgWp1FtzHXvf8jqSXwhYNIFYMFR2AoKm3HiWxHUvnT6cpP03MbD+kk1i0at73Wg7x5JFtsI5o9sIfPNnyFOSt6cafMLxk8JsAvJ2fNrRjyYmtDY19UcQQ+ocj5JYCfKS0OiDJozjiCbBydVphsLDMuNt/P5slYrbLjlmlwVC865Qu+k4w8N9QSmAFSH/Oih4e57EZDvz084FPaDPkBcXhIZjM8DOBDImQMp/w60Gzj6ohtytzDV+UpLjI9J9E9H4b+f4chs0yYy2uSxFYci8kVszR8B5xG1lJWag10vcBxzjKDIF2J3Pck/40LZmiY5xz19dEy1BW1LLRkvcCnQ=
  - secure: LKSabKqoa2XLJvmZHlHhMNLqgVHp59/Vp6yhYkgXQux/kncU/7NcJ1s9xsSQ7P3JwAVZMUMhrb34BUFyYMQ78RZp713p+1sjFHO7IeEiRhEQwGIzcqZOSqZ9VzEn5pJJO/jda30NoM2Gcgb9J+ljWaYS9n9Y2P2LRaJ5X0D7kBFhE1cY/eEVce2RmhmCYUn/mwa1KPzJGzGlrqYN/QUEG8P0Mm45rRV/xfzVy2gg0/S3il3MoljG/xixgcF5xGFvZO0+7CqZO2UfC17VjbirebDUeCy/roJTiwJazeIB0O4V41642yIvpd43MyeER1YZPXmnIWi/d1HOy/kusXi7j46o+TXCn7aWqk7ZWzcBoZR0k5W039OJN6/iSfrvhXbOepfcsPl5yklyXU/FW8WnY0F/+ZvHtxvlMGG/ZCbBtWUudOOZgnxWCnydLV4Ka8nerzL4M4wIw3ybiqkdnQ3V11o1QFDvo2kx/2eJ5y6/c6rbXe6pW+WBBgdqEx7YF1omqTRoZczUqQyjRtD3IPI7LL9cVYDXRpqEiezH1Al8UbM57VhkG1jwR1SDvrFDaYvh9lqs527/P7f1h9D5VZ51hpRXCUEc3oqVCTdwuiZuR74Tyc1Q/mHnkMsnuT/Gj6eauy5mc92n/LI2dyWLgzaJhqMWMrsVHap4OGbXbrxL1T0=
