language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
dist: trusty
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: fqZkMPlnaBQ6+4s/WdEBR/9NugFdX7ASMMGIdyr5WuXNLKcaseUQs7tyqDWOIHLzXt8ETWDnMO6Ky5orc5/kIA62Jcz91tm9i4qQd03B2vlZoLouMvwvfNT4WG0dVe9skH22pTArbD3mNX/V9WlL3OWP9fKBINPHTfMoThzRht/bmwdzTGDLNT89e8MWP3/0ZwoHMC8v54tZ9ORQHVjTqu0etIjpNDvzEulGD8HBRza+LnLxuGd0rqkknbEtMYP3M1PhLglIDn//frniYlU/T4l1cQRutJ0hwGN9V6pjyOuL6Zca7FHDvE93UrlMEuzrdHFXfp7oTyzklQe9zT8GNbx8n2QLOXqZTDiezyZQp4dDmZPXx5B60OWWhGhjV3IAAMLtn8nlJmGB+M0jlMjQufsUyO2VrGbFrATdZqcRXAdrKcVPcOgYtPcafOPUuogqA9Ng1WcW3OhtHJ7L0y2Oo+x4awo+55W9CkCE2eZgAGl41LeZryXcUj3xbmQkAYiBNQOSI6lkDhLx8QvRtgB3a5pWQXNPk/5fsbecGSCgEorpgmzu54sLCrH2mcVQYZ5+53AML6Y5sMNv8P1VFjML4AbXeAdo9gMpmoOX+d5tKFfZ5ytQwRGjLluET+W6tCtooDxWfLExp6GWCkR6eG/Mwepd+5lrIYxcIOzHaX2gYIs=
  - secure: vTvkiZJK6ow5kNgtiAh84LMCISzFcFqN0FlqlmnOsLC0TfyHgipAPWPTvNt2OYHkGojWRPwYMUJZ4w7omWP6QCux0LYJjyu6CyCeM1fH2s3ozmV3LapzL70PMow5tPNa+ioLIflZoQjtRFxQP5RZDpyYhgXY7zW0gv74BY08Jjfte7WkUZ13CJhRqS+cOXzE6/Z7JCJsi8/4XlnCTvTVFBqZoNJnD9UU0dhV57x+TmgbiAOFSWdHGNVbMnQPCHHYLMs1gWQjd2VWnpFs4+ZsB/W+i2kEO8NtS/vH/tmJ8qhXXT0R0E6dfOVM50wTBzrhP7DwmDQUO0eYswnGTEFnId3hVpw3ge0M/HAiGe0v0vBe8rcDKBSNpti0Fez5kJZPSpGxdXXteetJ3xawmDCkunuTlLa+dT2kFXR/NsIRCdH9HMyoFNbp3Oc7Wu3iJ22xDIF/dTQUOjzplM9c/aqy7zoy/IKP1YGWyClXsL4eDmvf1ryz3eypbA+fk/GU4YDEiTbpo7MQwMapPSxTl8XyhObdrX9ShP4ihsTKJtqgN0fhV/jCYgBxBcHXFfgjFUVOujxKKQPv/HV03lrmepBOLalhAM090WykYGXR625rkKGzIKCJIKTGXvgebxnCvlH8fG1T0lF46AjQyZHZWqrPA6v5luAM6g5Q+yFX7obdXq4=
