language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
dist: trusty
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: iV3h34h3AESX/pmEF/3SpeIliXLN+tHhvDVhnmfSHLyl3CjxpiTtL8Vl/iiJ1hlD2VzJZX77NqRoF3EgKCluHjKcwICMXLEOsRQkwQGuDKS54hkPmWAImf8zwye9hce2A4zQc/r+TJr055aP+JGETvT5fgDKyh6zYJny9Ozrn4+dzZqhEpjoAyCx9FBdDmUjP24GwQMIJT/og/KLZYw8fhW93QotCGHPRdnvXvIXoWm/zu0MIHFtFg2t9bAr45j19F8PHelmpZ5YLSykD9bFqdGLai4vgEVft4kLf/uVgCBp021a9vi5FM79fDbNjuU0sjOLo+CFDVTkPRE+/hzrAE0kzNlOL0TPqLIYsiHH+MDmkze1O3lntZVb7b6crUB3Cm7uF5P62cB3iK2E83+IN91k2A6tdkspTbGamsDnRUXJKzViEJ41TxS1AJ/IhA91WZjBgVE8cU17oXLt6JtjZc4buqxX2/DE467Aj9TK5565P87gmxGNM9k3RlpRmwFEYHO4nxiB3rtdc1E+zeOh/7yVMjXnQZP7OgMDRpdW5B9mq4sqs8gzYQQ5d1GFEkZuvzTUUwlPK+SEQ7ekDBFLjAxfedreB+jCfy6LE8vzJrfcYkA+c/OuMMszD1qHvQ+KXLXW4iRRq6uDcDdMLjsPR1ra39TKrwW3X9hOWlZpU7M=
  - secure: hrC1LDCXsGSybOGSBtf2ZwS+FbUllphTVWp05ZIf6VRwRberv/HP+f1rDZoS7oZLAl7WWEPRZoeC2275fSjk11JG9nfclC2cUw2XIHHozhFBr6lB5Iwdy/Fki5W1l9zEsdY4ifPqnt2YaHCgNmUtEn5hakgJ//AzvZ5VRAw81lwC0Mrk2+ShzT3/1KpaarcjT0mXtFUQ+ObOtMJO5Ng7DWa7QexIvJ264P7EBPsdImCrTuzzqXpienm/xXR929rpipYnof9LtOU+ntxaTYNuQVmLmfETYCImhSALss4bpqkYHlmJDff6ahzTawI2FZHrXsjm7pjPEK5nZA2iO45INrENGnn26e9N3O4FKihJ/MZM3AgGbKxGJvOVZyBQbrSQV7VjsNc5JzNiwvPulG/Dm6LxeopDPW+afmQP1RAWXzFauEwWM8pJyCHtPERyDeAX3p2HaBKaDLnFdvP+SenSvYdMSUJIsuo07ydUNTpV0DXcUBQ/2+9U2GNl4YtdN1/IyRBEwnjb2bLlHtRKwPb67hJBEDEMqVuey5cZd+iYEd/GWybSECsvFUdD2hvaY+DR8ERRdkU0T07vS8gfZFwj+i3RwsmSsarZ4LudGwxYo34+nEGV18Udzntn1hzhPLkfVfudanDujBpkqbqhoFybr6C2jyT15Wg7wP/DGg5pGK0=
